import 'package:get/get.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Go': 'Go',
      'You have pushed the button this many times:':
      'You have pushed the button this many times:',
      "Change language": "Change language",
      "Home Page": "Ínicio",
      "Second Page": "Segunda página",
      "Show": "Mostrar",
      "Change Theme": "Mudar tema",
      "home_search": "Procurar Lojas",
      "home_categories": "Categorias",
      "home_featured": "Abertos agora",
      "home_see_more": "Ver todas",
      "home_see_all": "Ver tudo",
      "home_restaurants": "Lojas perto de mim",
      "server_error": "Erro no servidor",
      "Login": "Login",
      "Email": "E-mail",
      "Password": "Palavra-passe",
      "Repetir Password": "Repetir Palavra-passe",
      "Sign Up": "Inscrever-me",
      "or": "ou",
      "Primeiro nome": "Primeiro nome",
      "Último nome": "Último nome",
      "Telefone": "Telefone",
      "Verify Otp": "Verificar Otp",
      "verify provide otp": "Verificar fornecedor otp",
      "verify_otp_sent": "Verificar otp enviada",
      "Type in your code": "Insira o código que recebeu",
      "Expires in": "Expira em",
      "next": "próximo",
      "please_fill_up_the_field": "Por favor preencha o campo",
      "O Menu Pedido": "O Menu Pedido",
      "Cart is Empty": "Carrinho está vazio",
      "Morada": "Morada",
      "A Tua Morada": "A sua Morada",
      "Agendar Entrega": "Agendar Entrega",
      "Agora": "Agora",
      "Detalhes do pedido": "Detalhes do pedido",
      "Item Total Price": "Total de produtos",
      "Discount Amount": "Valor de desconto",
      "Delivery Charge": "Taxa de entrega",
      "Total": "Total",
      "Please select a date and time slot":
      "Por favor selecione a data e hora que pretende receber a encomenda.",
      "Fazer Checkout": "Fazer Checkout",
      "Agendar entrega": "Agendar entrega",
      "Please select a time slot":
      "Por favor escolha uma intervalo de tempo",
      "Agendar": "Agendar",
      "Error": "Erro",
      "ALTERAR": "ALTERAR",
      "Checkout": "Checkout",
      "No data found": "Nenhum dado encontrado",
      "Agendar Entrega": "Agendar Entrega",
      "Detalhes do pedido": "Detalhes do pedido",
      "Pagar": "Pagar",
      "Payment": "Pagamento",
      "Special Instructions": "Instruções especiais",
      "Select Options": "Opções",
      "Addons": "Extras",
      "Add to cart": "Adicionar",
      "Failed to add product to cart": "A adição ao carrinho falhou",
      "Input Data": "Dados",
      "Input data is invalid": "Dados inválidos",
      "Verification Done": "Verificação concluída",
      "Please fill up all the fields": "Por favor, preencha todos os campos",
      "Name is required": "Nome é obrigatório",
      "Email is required": "E-mail é obrigatório",
      "Please enter a valid email": "Por favor, insira um e-mail válido",
      "phone_is_required": "Número de telefone é obrigatório",
      "Please enter a valid phone":
      "Por favor insira um número de telefone válido",
      "Password is required": "Password é obrigatória",
      "Passwords should have 8 length":
      "Password deve ter pelo menos 8 caracteres de tamanho",
      "Confirm password is required":
      "Confirmação de password é obrigatória",
      "Your passwords do not match": "As passwords não coincidem",
      "Empty Address": "Morada vazia",
      "No address Available": "Morada não disponível",
      "Adicionar Endereço": "Adicionar morada",
      "Failed to add product to cart": "Falha ao adicionar o produto ao carrinho",
      "add address": "adicionar morada",
      "Add Address": "Adicionar morada",
      "VEJA DETALHES": "Veja detalhes",
      "O Menu Pedido": "O Meu Pedido",
      "Detalhes do pedido": "Detalhes do pedido",
      "Histórico de pedidos": "Histórico de pedidos",
      "Pedidos Anteriores": "Pedidos Anteriores",
      "Address name is required": "Nome da morada é obrigatório",
      "Last name is required": "Último nome é obrigatório",
      "Latitude is required": "Latitude é obrigatória",
      "Longitude name is required": "Longiture é obrigatória",
      "Address  is required": "Morada é obrigatória",
      "Phone is required": "Telefone é obrigatório",
      "Adicionar Morada": "Adicionar Morada",
      "Endereço padrão": "Endereço padrão",
      "Nome Da Morada": "Nome da morada",
      "casa": "casa",
      "Morada/Ruaa": "Morada/Rua",
      "Localizaco atual": "Localizacão atual",
      "Código postal": "Código postal",
      "Código": "Código",
      "Código": "Código",
      "Estado": "Estado",
      "Cidade": "Cidade",
      "Guimares": "Guimarães",
      "Contacto": "Contacto",
      "NIF": "NIF",
      "Nift vazio": "Nif vazio",
      "Nif": "Nif",
      "Pedidas": "Pedidas",
      "Histórico de pedidos": "Histórico de pedidos",
      "Atualizar": "Atualizar",
      "Endereço de atualização": "Endereço de atualização",
      "Categories Empty": "Categorias vazias",
      "No Items available": "Produtos não disponíveis",
      "Nome de menus": "Nome de menus",
      "Total Price": "Valor total",
      "Finalizer Pedido": "Finalizar Pedido",
      "fetch_location_error": "fetch_location_error",
      "Please enable your location": "Por favor ative a localização",
      "Enable your gps": "Ative o gps",
      "Enable your gps": "Ative o gps",
      "okay": "Certo",
      "Cancel": "Cancelar",
      "Do you want to log out?": "Você quer sair?",
      "No item found": "Nenhum item encontrado.",
      "Total": "Total",
      "COMPLETED": "CONCLUÍDO",
      "Add Address": "Adicionar morada",
      "Special Instructions": "Instruções especiais",
      "Printing options: ": "Opções de impressão: ",
      "Please select payment method first": "Selecione o método de pagamento primeiro",
      "language_change_dialog_text": "Se quiser alterar a sua morada padrão, a alteração apagará todos os itens adicionados ao carrinho. Quer continuar?",
      "valid_phone_is_required: ": "Valid phone is required",
    },
    'pt_PT': {
      'Go': 'Go',
      'You have pushed the button this many times:':
      'You have pushed the button this many times:',
      "Change language": "Change language",
      "Home Page": "Ínicio",
      "Second Page": "Segunda página",
      "Show": "Mostrar",
      "Change Theme": "Mudar tema",
      "home_search": "Procurar Lojas",
      "home_categories": "Categorias",
      "home_featured": "Abertos agora",
      "home_see_more": "Ver todas",
      "home_see_all": "Ver tudo",
      "home_restaurants": "Lojas perto de mim",
      "server_error": "Erro no servidor",
      "Login": "Login",
      "Email": "E-mail",
      "Password": "Palavra-passe",
      "Repetir Password": "Repetir Palavra-passe",
      "Sign Up": "Inscrever-me",
      "or": "ou",
      "Primeiro nome": "Primeiro nome",
      "Último nome": "Último nome",
      "Telefone": "Telefone",
      "Verify Otp": "Verificar Otp",
      "verify provide otp": "Verificar fornecedor otp",
      "verify_otp_sent": "Verificar otp enviada",
      "Type in your code": "Insira o código que recebeu",
      "Expires in": "Expira em",
      "next": "próximo",
      "please_fill_up_the_field": "Por favor preencha o campo",
      "O Menu Pedido": "O Menu Pedido",
      "Cart is Empty": "Carrinho está vazio",
      "Morada": "Morada",
      "A Tua Morada": "A sua Morada",
      "Agendar Entrega": "Agendar Entrega",
      "Agora": "Agora",
      "Detalhes do pedido": "Detalhes do pedido",
      "Item Total Price": "Total de produtos",
      "Discount Amount": "Valor de desconto",
      "Delivery Charge": "Taxa de entrega",
      "Total": "Total",
      "Please select a date and time slot":
      "Por favor selecione a data e hora que pretende receber a encomenda.",
      "Fazer Checkout": "Fazer Checkout",
      "Agendar entrega": "Agendar entrega",
      "Please select a time slot":
      "Por favor escolha uma intervalo de tempo",
      "Agendar": "Agendar",
      "Error": "Erro",
      "ALTERAR": "ALTERAR",
      "Checkout": "Checkout",
      "No data found": "Nenhum dado encontrado",
      "Agendar Entrega": "Agendar Entrega",
      "Detalhes do pedido": "Detalhes do pedido",
      "Pagar": "Pagar",
      "Payment": "Pagamento",
      "Special Instructions": "Instruções especiais",
      "Select Options": "Opções",
      "Addons": "Extras",
      "Add to cart": "Adicionar",
      "Failed to add product to cart": "A adição ao carrinho falhou",
      "Input Data": "Dados",
      "Input data is invalid": "Dados inválidos",
      "Verification Done": "Verificação concluída",
      "Please fill up all the fields": "Por favor, preencha todos os campos",
      "Name is required": "Nome é obrigatório",
      "Email is required": "E-mail é obrigatório",
      "Please enter a valid email": "Por favor, insira um e-mail válido",
      "phone_is_required": "Número de telefone é obrigatório",
      "Please enter a valid phone":
      "Por favor insira um número de telefone válido",
      "Password is required": "Password é obrigatória",
      "Passwords should have 8 length":
      "Password deve ter pelo menos 8 caracteres de tamanho",
      "Confirm password is required":
      "Confirmação de password é obrigatória",
      "Your passwords do not match": "As passwords não coincidem",
      "Empty Address": "Morada vazia",
      "No address Available": "Morada não disponível",
      "Adicionar Endereço": "Adicionar morada",
      "Failed to add product to cart": "Falha ao adicionar o produto ao carrinho",
      "add address": "adicionar morada",
      "Add Address": "Adicionar morada",
      "VEJA DETALHES": "Veja detalhes",
      "O Menu Pedido": "O Meu Pedido",
      "Detalhes do pedido": "Detalhes do pedido",
      "Histórico de pedidos": "Histórico de pedidos",
      "Pedidos Anteriores": "Pedidos Anteriores",
      "Address name is required": "Nome da morada é obrigatório",
      "Last name is required": "Último nome é obrigatório",
      "Latitude is required": "Latitude é obrigatória",
      "Longitude name is required": "Longiture é obrigatória",
      "Address  is required": "Morada é obrigatória",
      "Phone is required": "Telefone é obrigatório",
      "Adicionar Morada": "Adicionar Morada",
      "Endereço padrão": "Endereço padrão",
      "Nome Da Morada": "Nome da morada",
      "casa": "casa",
      "Morada/Ruaa": "Morada/Rua",
      "Localizaco atual": "Localizacão atual",
      "Código postal": "Código postal",
      "Código": "Código",
      "Código": "Código",
      "Estado": "Estado",
      "Cidade": "Cidade",
      "Guimares": "Guimarães",
      "Contacto": "Contacto",
      "NIF": "NIF",
      "Nift vazio": "Nif vazio",
      "Nif": "Nif",
      "Pedidas": "Pedidas",
      "Histórico de pedidos": "Histórico de pedidos",
      "Atualizar": "Atualizar",
      "Endereço de atualização": "Endereço de atualização",
      "Categories Empty": "Categorias vazias",
      "No Items available": "Produtos não disponíveis",
      "Nome de menus": "Nome de menus",
      "Total Price": "Valor total",
      "Finalizer Pedido": "Finalizar Pedido",
      "fetch_location_error": "fetch_location_error",
      "Please enable your location": "Por favor ative a localização",
      "Enable your gps": "Ative o gps",
      "Enable your gps": "Ative o gps",
      "okay": "Certo",
      "Cancel": "Cancelar",
      "Do you want to log out?": "Você quer sair?",
      "No item found": "Nenhum item encontrado.",
      "Total": "Total",
      "COMPLETED": "CONCLUÍDO",
      "Add Address": "Adicionar morada",
      "Special Instructions": "Instruções especiais",
      "Printing options: ": "Opções de impressão: ",
      "Please select payment method first": "Selecione o método de pagamento primeiro",
      "language_change_dialog_text": "Se quiser alterar a sua morada padrão, a alteração apagará todos os itens adicionados ao carrinho. Quer continuar?",
      "valid_phone_is_required: ": "Valid phone is required",
    },
  };
}
